# Generated by Django 5.1.3 on 2024-12-02 09:13

import property_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='images',
        ),
        migrations.AlterField(
            model_name='accommodationimage',
            name='image',
            field=models.ImageField(upload_to=property_management.models.upload_accommodation_image),
        ),
    ]
