# Generated by Django 5.1.3 on 2024-12-02 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0002_remove_accommodation_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, size=None),
        ),
    ]
